version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/landingpage"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix"
    labels:
      - dependencies
      - security
    allow:
      - dependency-type: "all"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
